/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_inithelper_WRAP_H_
#define SWIG_inithelper_WRAP_H_

class Swig::Director;


class SwigDirector_TProgram : public TProgram, public Swig::Director {

public:
    SwigDirector_TProgram(PyObject *self, bool disown = false);
    virtual void outOfMemory();
    virtual void suspend();
    virtual void resume();
    virtual TPalette &getPalette() const;
    virtual void idle();
    virtual void getEvent(TEvent &event);
    virtual void handleEvent(TEvent &event);
    virtual void initScreen();
    virtual void putEvent(TEvent &event);
    virtual void run();
    virtual void shutDown();
};


class SwigDirector_TApplication : public TApplication, public Swig::Director {

public:
    SwigDirector_TApplication(PyObject *self, bool disown = false);
    virtual void outOfMemory();
    virtual void suspend();
    virtual void resume();
    virtual TPalette &getPalette() const;
    virtual void idle();
    virtual void getEvent(TEvent &event);
    virtual void handleEvent(TEvent &event);
    virtual void initScreen();
    virtual void putEvent(TEvent &event);
    virtual void run();
    virtual void shutDown();
};


class SwigDirector_TMethodHolder : public TMethodHolder, public Swig::Director {

public:
    SwigDirector_TMethodHolder(PyObject* self, bool disown = false);
    virtual TStatusLine *initStatusLine(TRect arg0);
    virtual TMenuBar *initMenuBar(TRect arg0);
    virtual TDeskTop *initDeskTop(TRect arg0);
};


class SwigDirector_TAppWrapper : public TAppWrapper, public Swig::Director {

public:
    SwigDirector_TAppWrapper(PyObject *self, TMethodHolder *arg0, bool disown = false);
    virtual void outOfMemory();
    virtual void suspend();
    virtual void resume();
    virtual TPalette &getPalette() const;
    virtual void idle();
    virtual void getEvent(TEvent &event);
    virtual void handleEvent(TEvent &event);
    virtual void initScreen();
    virtual void putEvent(TEvent &event);
    virtual void run();
    virtual void shutDown();
};


#endif
